# Generated by Django 5.2.8 on 2025-11-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='unit_preference',
            field=models.CharField(choices=[('metric', 'Metric (km, kg)'), ('imperial', 'Imperial (miles, lbs)')], default='metric', max_length=20),
        ),
    ]
