# Generated by Django 5.2.8 on 2025-11-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_unit_preference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='unit_preference',
        ),
        migrations.AddField(
            model_name='profile',
            name='distance_unit_preference',
            field=models.CharField(choices=[('km', 'Kilometers (km)'), ('miles', 'Miles')], default='km', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_unit_preference',
            field=models.CharField(choices=[('cm', 'Centimeters (cm)'), ('ft_in', 'Feet/Inches')], default='cm', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight_unit_preference',
            field=models.CharField(choices=[('kg', 'Kilograms (kg)'), ('lbs', 'Pounds (lbs)')], default='kg', max_length=10),
        ),
    ]
