# Generated by Django 5.0 on 2025-12-09 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_comment_workoutweather_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('milestone_type', models.CharField(max_length=50)),
                ('threshold', models.FloatField()),
            ],
        ),
    ]
