# Generated by Django 5.0 on 2025-12-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0004_usermilestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermilestone',
            name='seen',
            field=models.BooleanField(default=False),
        ),
    ]
